//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_Logs
    {
        public int ID { get; set; }
        public string API_Request { get; set; }
        public string User_Request { get; set; }
        public string Content_Request { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
