//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string GUID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Thumbnail { get; set; }
        public string IdCardNumber { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string TokenRegister { get; set; }
        public Nullable<System.DateTime> ExpireTokenRegister { get; set; }
        public string TokenLogin { get; set; }
        public Nullable<System.DateTime> ExpireTokenLogin { get; set; }
        public string TokenForgotPassword { get; set; }
        public Nullable<System.DateTime> ExpireTokenForgotPassword { get; set; }
        public string TokenDevice { get; set; }
        public string TokenAutoLogin { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsVerifyEmail { get; set; }
        public Nullable<bool> IsVerifyPhone { get; set; }
        public string Balance { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsBanned { get; set; }
        public Nullable<System.DateTime> DateBanned { get; set; }
        public string ThumbLicense { get; set; }
        public string ThumbAvatar { get; set; }
        public string ThumbIdCard { get; set; }
        public Nullable<int> MajorID { get; set; }
        public Nullable<int> Sex { get; set; }
        public string TokenFacebook { get; set; }
    
        public virtual GroupUser GroupUser { get; set; }
        public virtual Major Major { get; set; }
    }
}
